### ISSUE TITLE
Front - Levantamento para Cronograma da Matriz Logica

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#190]
Realizar um pesquisa de quais os plugins existente e viáveis para implementar no projeto na sessão de cronograma da Matriz Logica. 

O plugin consiste em apesentar um Gantt Chart com as seguintes funcionalidades:

•	Função de Zoom (anual, semestral, trimestral, diário)
•	ThreeList (categorizar) das atividades
•	Imagens dos responsáveis por pelas atividades~
•	Menu Dropdown

**Comment by Clivisonc** [comment]
Levantamento de componentes e funcionalidades para uso na funcionalidade de Matriz Lógica.

**Comment by ricardosreichert** [comment]
Ganttastic - 100% FREE
https://infectoone.github.io/vue-ganttastic-homepage/#/

Gantt Elastic – Free/Trial
https://gantt-schedule-timeline-calendar.neuronet.io/

Vue Gantt - Free/Trial
https://www.vue-gantt.com/

Em reunião junto com o Daniel Lazaroni concluimos que utilizando apenas a opção FREE (Ganttastic ) teriamos as funcionalidades basicas necessarias.
