### ISSUE TITLE
Front - Alerta de Sucesso ou Falha

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#227]

**Comment by ricardosreichert** [comment]
Tipo Alerta INFO
![image.png](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/07e85ce6-c044-43a7-acfe-bffe0ecd4965)

Tipo Alerta WARN
![image.png](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/881c23f4-7c83-4c1d-81c0-2461703b5662)

Tipo Alerta ERROR
![image.png](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/0e1b1aa6-4a69-4d60-ace5-9ecd716e2a92)

Tipo Alerta SUCCESS
![image.png](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/fae3431a-e4bb-4ba3-954b-709e65fd0811)

Commit LINK
https://github.com/UNICEF01/Sistema-MAAp-front/commit/4196076b04c4f32f8d5dadc6603c66e1425618a0
