### ISSUE TITLE
Levantamento de Esforço - Matriz Lógica e Projeto

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#232]

**Comment by ricardosreichert** [comment]
https://unicef-my.sharepoint.com/:u:/g/personal/rreichert_unicef_org/EX-lWoibu9RGjdEPHFDo_XkBRxgb5molHNGgNU7Ja21Mbw

https://unicef-my.sharepoint.com/:u:/g/personal/rreichert_unicef_org/EcCb39omwuRDjzNMsud161UBPKwUo_c52CHP_Isu_4EtLw

![maap_db.png](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/1283a573-1e49-436d-88f7-1c7ceabbb328)
