### ISSUE TITLE
Formulário de Criação/Edição de Programas - Informações Gerais - Front

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#248]
- [x] Tipo de Instrumento - RadioButton
- [x] Título e Descrição do Programa - Campo Texto
- [x] Campos de Previsão de Início e Término - Calendar
- [x] Critério de Validação - Campo data efetiva de início e término - Calendar (Apenas no modo de edição)
- [x] Critério de Validação - Data de início (Previsão/Efetiva) no passado

**Comment by ricardosreichert** [comment]
Formulário de Informações Gerais pronto para Criar e Editar um programa
https://github.com/UNICEF01/Sistema-MAAp-front/commit/29cc7fd857d3a4be5df7519909bdd7e3065c2c23
