### ISSUE TITLE
Formulário de Criação/Edição de Programas - Instituições e Usuários - Front

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#249]
- [x] Seleção de Instituição Parceira - Dropdown
- [x] Adicionar Instituição - Button
- [x] Busca e seleção de usuários - Dropdown com busca
- [x] Atribuir permissão - Dropdown
- [x] Adicionar Usuário - Button - O primeiro usuário cadastrado, por instituição, por default, será do tipo administrador.
- [x] Remover Usuário - Button
- [x] Critério de Validação - Cada instituição precisa ter, no mínimo, um usuário administrador. Mensagem de erro por não ter um usuário administrador cadastrado em alguma(s) da(s) instituições.
- [ ] Modal de confirmação de criação do Programa
- [x] Mensagens de alerta (Sucesso de Criação e Sucesso de Exclusão)

**Comment by ricardosreichert** [comment]
**Componente para adicionar usuarios a um programa**
- Seleção de Instituição Parceira - Dropdown
- Adicionar Instituição - Button
- Busca e seleção de usuários - Dropdown com busca
- Atribuir permissão - Dropdown
- Remover Usuário - Button
-  Remover Usuário - Button

https://github.com/UNICEF01/Sistema-MAAp-front/commit/9992f8b8a06b43204dcc328633f18872ab193a0b

**Comment by ricardosreichert** [comment]
**Validações no formulario**

- Mensagens de alerta (Sucesso de Criação e Sucesso de Exclusão)
- Critério de Validação - Cada instituição precisa ter, no mínimo, um usuário administrador.
- O primeiro usuário cadastrado, por instituição, por default, será do tipo administrador.

https://github.com/UNICEF01/Sistema-MAAp-front/commit/3e6d112a735990dacf2f873ad59cb8e4bcb17939
