### ISSUE TITLE
Formulário de Criação/Edição de Projetos - Adicionar Projeto/Modalidade/Relacionamento com programas - Front

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#261]
- [x] Título - Campo Texto
- [x] Nome Comunicacional - Campo Texto
- [x] Tipo de Modalidade: Selectbutton
- [x] Descreva sobre... - Campo Texto
- [x] Relacionamento com os programas - Dropdown multiselect com campo digitável

**Comment by ricardosreichert** [comment]
- [x]  Título - Campo Texto
- [x]  Nome Comunicacional - Campo Texto
- [x]  Tipo de Modalidade: Selectbutton
- [x]  Descreva sobre... - Campo Texto
- [x]  Relacionamento com os programas - Dropdown multiselect com campo digitável

https://github.com/UNICEF01/Sistema-MAAp-front/commit/6d8a08d22144ccd24794fb4d981bdce6852a5d11

![image.png](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/a2df9f0d-065b-4c67-beb8-f95508e92755)
