### ISSUE TITLE
Implantação do Novo Domínio - Ajustes no Servidor

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#266]
- [x] Atualizar o Domínio no Servidor (Front e Back)
- [x] Atualizar as variáveis de ambiente (Front e Back)
- [x] Atualizar o Script de Implantação do Back
- [x] Adicionar as Credenciais do Mailgun

**Comment by ricardosreichert** [comment]
URLs de Produção Atualizadas

> maap.rsr.dev.br --> **maap.org.br**
> api.maap.rsr.dev.br --> **api.maap.org.br**
> dbadmin.maap.rsr.dev.br --> **dbadmin.maap.org.br**

**Comment by ricardosreichert** [comment]
![image.png](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/1b5f143d-b320-431a-94f6-988c85656c56)
