### ISSUE TITLE
Front - Listagem de Projetos

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#271]
- [x] Reutilização da Página de Listagem de Programas
- [x] Alteração da nomenclatura dos campos 
- [x] Alteração da integração

**Comment by ricardosreichert** [comment]
- [x] Reutilização da Página de Listagem de Programas
- [x] Alteração da nomenclatura dos campos
- [x] Ajustes e criação de novos métodos de consulta para a API

https://github.com/UNICEF01/Sistema-MAAp-front/commit/afa12014856e29bcb138e122b60bf57bc13ba705

**Comment by ricardosreichert** [comment]
- [x]  Alteração da integração


https://github.com/UNICEF01/Sistema-MAAp-front/commit/74a84b0181ce87b5ae30c4ad60f155bfa7edf7bd
