### ISSUE TITLE
Front - Cadastrar - Matriz Lógica

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#273]
- [x] Título - Campo Texto
- [x] Descrição - Campo Texto
- [x] Tela de Matriz Não Existente (Validação)

**Comment by ricardosreichert** [comment]
- [x] Título - Campo Texto
- [x] Descrição - Campo Texto
- [x] Tela de Matriz Não Existente

https://github.com/UNICEF01/Sistema-MAAp-front/commit/cbc5c4a9d71b9a7f8b75031c40499b493a904c5c
