### ISSUE TITLE
[FRONT] (GLOBAL) Listagem de todos os indicadores, separados por categoria (projeto/programa).

### ISSUE THREAD

**Issue by cxelegance-unicef** [UNICEF01/MAAP#310]
Regras:
- Separar a listagem entre projeto e programa.
- Pesquisar indicador por titulo.
- Paginação separada por Projeto/Programa.

Duvidas:
- Quando um indicador possui mais de um programa/projeto, como devemos tratar os links na coluna ações?
- - Colocar um link por cada Resultado/Produto do Indicador.

**Comment by ricardosreichert** [comment]
@lucasferreiraunicef Temos um duvida descrita na descrição dessa tarefa.
