### ISSUE TITLE
[BACK] (FORMULARIO) Cadastrar e Editar um indicador

### ISSUE THREAD

**Issue by cxelegance-unicef** [UNICEF01/MAAP#316]
Regras:
- Listagem de Resultados por ID de projeto/programa com Simple.
- Listagem de Produtos por ID de projeto/programa com Simple.
- Criar e Editar tem que processar Resultados e Produtos.

Duvida:
- No formulario diz que os Resultados/Produtos são da Matriz Logica, devem ser da Matriz ou do Programa?
- - Supomos que os Resultados/Produtos são de Programas.

**Comment by ricardosreichert** [comment]
@lucasferreiraunicef  Temos um duvida descrita na descrição dessa tarefa.

**Comment by lucasferreiraunicef** [comment]
Dúvida respondida.
