### ISSUE TITLE
Resultado

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#321]
Resultado(Futuro)(Algo que eu espero atingir):  
É o que o usuário espera atingir de resultados para aquele objetivo específico previamente definido. 

**Descrição:** 

**Regra de negócio:**
**Programa:**
Eu crio resultados e os relaciono com os objetivos específicos criados.(Obrigatório) - (2 nível matriz lógica)
Relaciono com um ou mais indicadores (Opcional)
[Matriz Logica - Resultados](https://xd.adobe.com/view/6ea356df-f452-4ff7-b64a-13446059146c-3bf0/screen/57c9657a-3b64-414e-b850-772c30a3104d/)
Tela 7 a 17.

**Projeto** 
Eu crio resultados sem os relacionar com objetivos específicos, haja visto que tal referencia se dará na matriz lógica do projeto. (1 nível matriz lógica)
Tela 1 e 2

[Matriz Logica - Resultados](https://xd.adobe.com/view/c6c20f80-a0d2-4ee5-9d6c-1dcf0cc8486d-9391/)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

- [ ] Deve seguir o fluxo correto da jornada do usuário

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo.

**Comment by ricardosreichert** [comment]
@dlazaroni @lucasferreiraunicef 
Estamos com uma duvida!

Uma solução que encontramos para o problema de armazenar os indicadores é criar uma copia e salvar com as edições feitas no formulário de resultados. Porem o que não é ideal é que teremos na listagem de indicadores mais de um indicador com o mesmo nome/titulo.
