### ISSUE TITLE
Matriz Lógica

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#352]
**Description:**  Desenvolver a Visualizacão de Matriz Logica para **PROGRAMAS** & **PROJETOS**.

**Programas:**

Desenvolver a VIEW com a listagem de Matriz Logica com os devidos componentes de tela apresentados na imagem e protótipo abaixo.

[Link](https://xd.adobe.com/view/6ea356df-f452-4ff7-b64a-13446059146c-3bf0/screen/34553edb-6744-470c-8712-7d45a86eddd0/) - TELA 26

**Regra de negócio:**

Cabeçalho: Título, Objetivo Geral, Qtde de "Objetivos específicos", Qtde de "Resultados", Qtde de "Produtos", Total Contrapartida financeira, Total Contrapartida não financeira. **Ações: editar e remover(Disable em cascata)**

**Obs:** 
**Regra de Contribuição não financeira e financeira ->** 
Resultado é igual a soma dos valores de seus produtos
Objetivo Específico é a soma dos valores de seus resultados
O Total de Contrapartida financeira e não financeira é a soma dos valores de seus objetivos específicos

**Projetos:**

Desenvolver o CRUD de Matriz Logica para Projetos e seus devidos componentes e adaptações:

**Adaptar resultado e produto da matriz logica para projeto -> Tela 2 e 3**

Cabeçalho: Impacto (título de Objetivo Específico, Resultado e/ou Produto); Indicadores (títulos dos indicadores; Metas; Previsão de início; Previsão de fim; Contrapartida não financeira; Contrapartida financeira; **Ações (editar / remover(Disable em Cascata) - por linha)**

**Regra de Contribuição não financeira e financeira ->** 
Resultado é igual a soma dos valores de seus produtos
O Total de Contrapartida financeira e não financeira é a soma dos valores de seus resultados

[Link](https://xd.adobe.com/view/9d5736a5-4d78-4f62-a8fc-6d2625233a3d-c804/) - TELA 1 a 3

**Itens fora do escopo da User Story:**

- Tour 

- Duplicação de Matriz

- Possibilidade de criar Matriz para um mesmo **programa** e para um mesmo **projeto**

- Ativar/Desativar

**Comment by cxelegance-unicef** [comment]
@lucasferreiraunicef @dlazaroni 
Duvidas agora:
- Na tela: tem colunas: indicadores e metas: o que fazer com esses?
  - De onde vem os dados?
  - o que fazer com clique?
- Pra client: que tal ação "desativa" simplesmente esconda o item e subitems sendo desativados?

**Comment by dlazaroni** [comment]
@cxelegance-unicef 

Na tela: tem colunas: indicadores e metas: o que fazer com esses?
De onde vem os dados? **R: Só exibe se tiver indicador e meta relacionado** 
o que fazer com clique? **R: Propus uma modal para exibir a lista de indicadores ou metas, enviei um vídeo para o Ricardo** 
Pra client: que tal ação "desativa" simplesmente esconda o item e subitems sendo desativados? **R: O difícil de esconder é como ele vai encontrar novamente, né? Tinha até pensado em uma interface pra exibir os itens "escondidos", mas precisamos discutir melhor. Print anexo** ![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/1c866509-5ccc-4957-a01d-1d13dc211e2d)

**Comment by cxelegance-unicef** [comment]
@dlazaroni _Pra client: que tal ação "desativa" simplesmente esconda o item e subitems sendo desativados?_ A gente tá tentando evitar a cascata de desativação. Outra opção em vez de esconder o item e todos os subitens, poderiamos botar o item e todos os subitens em cinza (UI desativada). Bom, discutamos melhor ;)

**Comment by lucasferreiraunicef** [comment]
Concordo com o Dan. Mas veja, em bate papo com o Niklas, o mesmo apontou que seria interessante a "Desativação" em cascata. Ainda hj teremos a resposta definitiva.
________________________________
De: cxelegance-unicef ***@***.***>
Enviado: quinta-feira, 2 de fevereiro de 2023 13:49
Para: UNICEF01/MAAP ***@***.***>
Cc: Lucas Ricardo Ferreira Rocha ***@***.***>; Mention ***@***.***>
Assunto: Re: [UNICEF01/MAAP] Matriz Lógica (Issue #352)


@dlazaroni<https://github.com/dlazaroni> Pra client: que tal ação "desativa" simplesmente esconda o item e subitems sendo desativados? A gente tá tentando evitar a cascata de desativação. Outra opção em vez de esconder o item e todos os subitens, poderiamos botar o item e todos os subitens em cinza (UI desativada). Bom, discutamos melhor ;)
