### ISSUE TITLE
[Work Plan + Timeline] Atividades

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#356]
**Descrição:** Uma atividade deve estar relacionada a uma iniciativa criada do plano de trabalho. Ela deve relacionar os usuários que estão como responsáveis pela mesma, além de alterar o progresso e relacionar os indicadores relacionados a seu programa/projeto.

![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/a0f20351-2b92-499d-a1a5-fc712b284363)
**Link:** https://xd.adobe.com/view/7561e78f-c84e-4849-862e-8bdec4ca7a7b-2032/screen/4ba79fa6-94d3-48d6-aa73-2b08fd568c36/specs/ (Telas de 6 a 8)

**Regras de negócio:**
- Há variações de telas a partir do progresso selecionado. Quando o progresso é "Concluída", aparece a possibilidade de indicar a data de conclusão, bem como o campo de orçamento executado, além de um campo aberto de observações.
- No list/view, as atividades cadastradas, devem ser visualizadas dentro da iniciativa a qual ela está relacionada
- Os usuários responsáveis devem ser exibidos a partir do universo de usuários que estejam com algum tipo de permissão no programa/projeto e que façam parte da(s) instituição(ões) que estejam relacionadas na iniciativa na qual a atividade faz parte.

**Não entra para esse épico:**
- Upload de arquivos;
- Itens de orçamento (orçamento alocado e orçamento executado)
- Campo "possibilidades de alertas" (esse será adicionado ao épico de [Notificações](https://app.zenhub.com/workspaces/maap-1-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/367))

**Comment by cxelegance-unicef** [comment]
Olá @dlazaroni, eu não consigo ver todos os termos de "progresso" no XD. Eu peguei o seguinte e escolhei "em andamento" como default/padrão. Cê pode corrigir e adicionar o quarto termo em falta?

$table->enum('progresso', ['Concluída', 'Interrompida', 'Em andamento'])->default('Em andamento');

Também, cê pode me dar os termos de "prioridade" e qual é default/padrão?

Grato!

**Comment by dlazaroni** [comment]
@cxelegance-unicef Jesse, desculpe pelo não funcionamento adequado do protótipo para que você pudesse ver todos os itens do campo. Segue o print:
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/8a0b3949-6c85-4540-a7fd-abc8e0a119aa)

Default: Não iniciada

$table->enum('progresso', ['Não iniciada', 'Em andamento', 'Concluída', 'Interrompida'])->default('Não iniciada');

**Comment by cxelegance-unicef** [comment]
Obrigado @dlazaroni ! Também, cê pode me dar os termos de "prioridade" e qual é default/padrão?

**Comment by dlazaroni** [comment]
@cxelegance-unicef 
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/ec3b0167-7951-40b1-93bf-cbcad85221b5)
Padrão: 'Média'
