### ISSUE TITLE
[Monitoramento PROGRAMA]

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#358]
Description: Trata-se de um registro para acompanhamento do andamento dos **PROGRAMAS** conforme o **planejamento**.   

Link: https://xd.adobe.com/view/510713cf-5f09-4d90-96e3-d952b659fdce-0454/specs/

Regra:

Formulário de Cadastro(Monitoramento):

Status geral: 
PONTO DE ATENÇÃO: quando qualquer um dos três status acima selecionado que estiver marcado com "PONTO DE ATENÇÃO";
DENTRO DO ESPERADO: quando todos os três status acima selecionados estiverem marcados com "DENTRO DE ESPERADO";
ACIMA DO ESPERADO: quando pelo menos um dos três status acima estiver marcado com "ACIMA DO ESPERADO" e não haver nenhum com o status "PONTO DE ATENÇÃO"

Endpoint List User: https://api.maap.org.br/api/programa/1

**Comment by lucasferreiraunicef** [comment]
@dlazaroni Dan, pode postar o link do MONITORAMENTO por gentileza? Certifique-se de que esteja de acordo com as últimas definições da reunião do dia 22/06. Encaminho abaixo a definição:

**Monitoramento**:
Desenvolvimento de todo o formulário
Excluir o gráfico
Inserir upload com a regra de permissão padrão

**Comment by dlazaroni** [comment]
@lucasferreiraunicef Link adicionado na descrição do épico

**Comment by lucasferreiraunicef** [comment]
Obrigado Dan.

**Comment by mfreireunicef** [comment]
@dlazaroni @lucasferreiraunicef Preciso saber da regra para as cores desses status

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVNLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a91bbcd304a431edceec7ffe133047628cd24a35/Captura%20de%20Tela%202023-09-11%20a%CC%80s%2017.27.27.png)

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef 
Estes "STATUS" representam a média final presente no final do form de **"MONITORAMENTO"**.
Sendo assim:
Azul - ACIMA DO ESPERADO
Verde - DENTRO DO ESPERADO
Vermelho - PONTO DE ATENCÃO
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXVWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a082579100896de19cb2ef52df6005d4fc829ebd/Captura%20de%20Tela%202023-09-13%20a%CC%80s%2009.19.26.png)

**Comment by mfreireunicef** [comment]
Obrigado @lucasferreiraunicef
