### ISSUE TITLE
Homologação indicadores

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#365]
- [x] Linha base inicial (valor): permitir caracteres que não sejam números (%)

- [x] Ao adicionar uma meta anual de um ano X, esse ano não deve aparecer como disponível novamente na adição de uma outra meta anual;

- [x] Ao salvar um indicador novo ou editar um já existente, a página deve ser direcionada para listagem de indicadores. No meu caso eu estava acessando uma página de listagem de programa e acessei a url de criação do indicador diretamente no navegador e quando eu salvei o indicador novo a página voltou para a que eu estava.

- [x] Na lista de programas e projetos adicionar link de indicadores nos três pontinhos.

- [x] Listagem e edição de projetos quebrou após o deploy;

- [x] Linha Base do componente de Indicadores deve ser autopreenchida e bloqueada.

- [x] Meios de Verificação e do componente de Indicadores.

- [x] Modal de confirmação de remoção de um item da lista do componente de Indicadores.

**Comment by ricardosreichert** [comment]
- Ao adicionar uma meta anual de um ano X, esse ano não deve aparecer como disponível novamente na adição de uma outra meta anual;
https://github.com/UNICEF01/Sistema-MAAp-front/commit/5f84d5c085464e8df23bdfb1a32b6e96927a4d79


- Ao salvar um indicador novo ou editar um já existente, a página deve ser direcionada para listagem de indicadores. 
https://github.com/UNICEF01/Sistema-MAAp-front/commit/90a0ce110df0491274097c8d947cdb0459047dc8


- Na lista de programas e projetos adicionar link de indicadores nos três pontinhos.
https://github.com/UNICEF01/Sistema-MAAp-front/commit/09307155633305b36d0bf5edbea97989d49ee02d


- Modal de confirmação de remoção de um item da lista do componente de Indicadores.
https://github.com/UNICEF01/Sistema-MAAp-front/commit/36e6270c77122330804bd99c78f553965cb952b4


- Linha Base do componente de Indicadores deve ser autopreenchida e bloqueada.
- Meios de Verificação e do componente de Indicadores.
https://github.com/UNICEF01/Sistema-MAAp-front/commit/d3ba948758747edd1d24b3652e20427df7407e45

- Linha base inicial (valor): permitir caracteres que não sejam números (%)
https://github.com/UNICEF01/Sistema-MAAp-front/commit/d176d1560c01a8de468ee63038451cad9dd7a2ce
