### ISSUE TITLE
[PERMISSIONS] Programa e Matriz Lógica de Programa

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#373]
**Description:** Os grupos de permissões atrelados as Roles estão listados abaixo.

**Regra de Negócio:**

Programa & Matriz Lógica Programa
	- Criar
	- Editar
	- Excluir	
	- Visualizar
	- Aprovar

----

**Programa:** 

A visualização de **PROGRAMAS** e **MEUS PROGRAMAS** devem ser mostradas (Show) para todos os usuários em que sua instituição esteja com qualquer usuário relacionado. A Aplicação das permissões serão aplicadas a partir do momento em que o usuário tomar alguma ação, exemplo: Editar, Visualizar ou Remover.

Para melhor entender sob quais componentes aplicaremos a visualização de acordo com a permissão do Current_user(Usuario), segue abaixo um fluxo com o que deve ser visualizado em cada tela ou fluxo de navegação do usuário. 

**OBS:** DEVERÁ SER APLICADA EM CASCATA 

![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/1a647317-9d6b-4209-8a06-62890ec62863)
[https://miro.com/app/board/uXjVOEyNfBY=/](https://miro.com/app/board/uXjVOEyNfBY=/ )

Visualização do MENU (De acordo com a permissão)  

**Listagem Geral de Programas** 

Na listagem de programas, de acordo com a PERMISSÃO do usuário logado, alguns itens do Menu abaixo não devem aparecer. 

Exemplo: Se eu estiver com a permissão de VISUALIZACÃO, não poderei visualizar o submenu de “Editar” e “Remover programa”   
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/6c64490e-f94c-48ba-9838-4bcf5765dd17)

**Listagem de MEUS PROGRAMAS** 
Na listagem de MEUS PROGRAMAS, a regra acima se aplica com a mesma narrativa.

Exemplo: Se eu estiver com a permissão de VISUALIZACÃO, não poderei visualizar o submenu de “Editar” e “Remover programa”
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/3176eca6-248d-4859-bc6e-ebbfb04c745d)

*OBS:* qualquer usuário pode adicionar programas ou projetos, independente de permissões.

**//MEGA OBS// ANALISAR VIABILIDADE DE SUPER-ADMIN** ![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/5de6b7af-310d-4d73-a630-d6ccc6290c08)

---

**Layouts para a permissão de visualização (leitor):**

**Listagem de PROGRAMAS:** ![listagem-programas-visualizador.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/3fb315bf-cf09-4c98-a94d-1bfcdd02a033)
URL: https://maap.org.br/programs

**Visualizar PROGRAMA:** ![visualizar-programa.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/abe261a2-bbc1-47d6-98d4-300dd7f0d4ca)
URL: https://maap.org.br/program/2

**Listagem de INDICADORES:** ![listagem-indicadores-visualizador.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/bd3be46e-2fa9-4d78-818a-7fe660498d98)
URL: https://maap.org.br/program/1/matriz/1/indicadores

**Visualizar INDICADOR:** ![visualizar-indicador.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/7e4ec78f-d2e6-439e-b830-a96ef2a1dcd1)
URL: https://maap.org.br/program/1/matriz/1/indicador/1
SVG Icon EYE: ![eye.svg](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/14e7fd5f-ba1d-480e-b017-8d3e45aeed19)

**Visualizar Matriz Lógica » Objetivo Específico:** ![visualizar-matriz-objetivo-especifico.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/af214b25-3473-4cc6-a179-d54e68c58058)
URL: https://maap.org.br/program/1/matriz/1/objetivo-especifico/1

**Visualizar Matriz Lógica » Resultado:** ![visualizar-matriz-resultado.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/52b27cb8-7378-4d56-a863-489e93e2cd65)
URL: https://maap.org.br/program/1/matriz/1/resultado/3

**Visualizar Matriz Lógica » Produto:** ![visualizar-matriz-produto.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/875141ef-8065-4a1d-ac8e-6a9beee309fe)
URL: https://maap.org.br/program/1/matriz/1/produto/1

**ATENÇÃO:** Para todas as telas de visualização de uma página que seria de edição (ex: Visualizar INDICADOR, Visualizar PROGRAMA, Visualizar Matriz Lógica » Resultado, etc...), adicionar o bloqueio dos campos de input, conforme print abaixo:
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/f979ff90-a5de-4e5c-801b-fe9433391bd0)
Já utilizamos esse ícone de bloqueado no cursor para os campos "linha base inicial (data)" e "linha base inicial (valor)" do formulário de Produtos: https://maap.org.br/program/1/matriz/1/produto/1

**Comment by mfreireunicef** [comment]
Devido a inconsistencia dos dados, não foi possivel implementar parte dessa demanda da melhor maneira. Issue: [#425](https://app.zenhub.com/workspaces/maap-2-63bda994ef4022001bac3ed9/issues/gh/unicef01/maap/425)

Quando recupera o ID do usuario logado não é possível validar a permissão do mesmo, visto que os ARRAYS de projeto e programa não retornam os dados dos usuários relacionados ao projeto/programa no componente de MATRIZ LÓGICA. Isso é necessario para validar a permissão do usuario logado.

Alem disso, diversas vezes os dados oscilam, respondendo as vezes sim as vezes não, talvez devido ao grande numero de requisições (muitas repetidas ou sem necessidade). Necessario revisar algumas partes(requisições) da arquitetura do projeto.
