### ISSUE TITLE
[BACK] Produto: modificar banco de dados: com testes

### ISSUE THREAD

**Issue by cxelegance-unicef** [UNICEF01/MAAP#382]
## "produto" table e relacões existentes
- [X] O campo "resultado_id" basta; é select simples. ~~Implementar "produto_resultado" relational table for multi-select on form~~
- [X] O campo "obj_especifico_id" basta; é select simples. ~~Implementar "produto_objetivo" relational table for multi-select on form~~
 - see [#380](https://app.zenhub.com/workspaces/maap-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/380)
- [x] Mudar nome do campo: iniciativa_direito_da_crianca -> comentário_direito_da_crianca
- [x] Implementar campo: iniciativa_direito_da_crianca [BOOLEAN] default FALSE
- [x] Implementar campo: comentário_igualdade_genero [VARCHAR]
- [x] Usar 'produto_ods' (já existe) relational table for "Objetivos de Desenvolvimento Sustentável" multi-select on form

## "produto_contribuicao_financeira" relational table
- see [#379](https://app.zenhub.com/workspaces/maap-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/379)
- [ ] Implementar "produto_contribuicao_financeira" relational table
- [ ] Incluir campo na tabela "produto_contribuicao_financeira": ano
- [ ] Modificar tabela "contribuicao_financeira" pra ter campo "contrapartida_financeira" opcional (nullable)

## Tudo/fim
- [ ] testes atualizados e passando

**Comment by cxelegance-unicef** [comment]
@dlazaroni @ricardosreichert Olá colegas! Tô querendo confirmar as pontas em cima marcado **clarificar** e **confirmar**. 

Pra mim, não é claro se _resultados_ é só um select ou é multi-select. No #380 parece só um mas no XD parece multi-select.
Queria confirmar também que _objetivo especifico_ é multi-select.

Queria confirmar a necessidade duma tabela relacional _produto_contribuicao_financeira_ para relacionar _produto_ com tabela _contribuicao_financeira_, e que nessa nova relacionamento precisamos dum novo campo _ano_.

**Comment by dlazaroni** [comment]
@cxelegance-unicef Pode considerar "Resultado" e "Objetivo específico" como um select simples mesmo.

Sobre a dúvida de contribuição financeira, entendo que é necessário sim.

**Comment by cxelegance-unicef** [comment]
@dlazaroni ok, obrigado!
