### ISSUE TITLE
[BACK] botar campo "deactivated_at" em várias tabelas; implementar desativar CASCADE

### ISSUE THREAD

**Issue by cxelegance-unicef** [UNICEF01/MAAP#400]
tabelas:
- [x] matriz logica -> trocar "ativo" pra "deactivated_at"
- [x] indicadores (olhe em várias relações) -> trocar "ativo" pra "deactivated_at"
- [ ] ~~plano_de_trabalho (não existe mais)~~
- [x] objetivo_especifico (relacões: resultado, produto)
- [x] resultado (relações: produto)
- [x] produto (relações: projeto, plano de trabalho, mais?)
- [ ] ~~projeto: refactor pra GET withInactive pra incluir produtos ou outros desativadas nos resultados~~

Deactivation:
- [x] Cada Serviço dessas tabelas precisa dum "desativar" método que faz desativação CASCADE pelas chaves estrangeiros. Qualquer "filho" Serviço que BelongsToMany "pai" Serviço pode ser desativado só senão tiver outras BelongsToMany relações entre o "filho" e outros "pai"; num caso assim, só apagar as relações entre o "filho" e o "pai", deixando as outras relações com os outros "pai".

Note:
- [x] **IMPORTANTE** _Esse campo "deactivated_at" (data) tem que ser opcional com padrão NULL_: porque? Porque tem já muito formulário que existe que não sabe nada desse campo.

**Comment by cxelegance-unicef** [comment]
Olá @dlazaroni! A gente tem uma dúvida. Quando a gente desativa um produto, pode ter projetos relacionando com o produto. A gente desativa o projeto também?

**Comment by cxelegance-unicef** [comment]
@lucasferreiraunicef @dlazaroni @ricardosreichert 

Sorry for the English! But I needed to dump this summary of my meeting with Ricardo here, rapidinho.

> I met with Ricardo this morning after the Daily. I've been updated that the decision with the client was that when an item is deactivated, the backend continues to cascade and deactivate subitems; if a subitem is related to some other item outside of the current context/scope, then rather than deactivate that subitem, the relation between the top item and the subitem is deleted.
> 
> This causes a problem. The problem is we have now deleted some information; originally, there was a relationship between items and now it is gone. We believe this is not what the client would want. The client would want to keep the structure of the item and its subitems and deactivate it without losing any information (in this case, losing subitems in the context of the parent item).
> 
> Ricardo suggested a solution to this problem: why not deactivate the relationship between the items rather than delete it. That would work, yes! Except that we have a problem: the way all updates to items/entities are working in the backend is this: new relationships are formed and old relationships are deleted. That means that if an update is ever sent to the backend that affects an item whose relationship has been deactivated, that relationship record containing the deactivation information will be deleted. It will be replaced with a normal relationship record (active). To change this would be to change it in multiple update locations in the code.
> 
> What is the business case for knowing when any item has been deactivated? Is there always going to be a context? E.g., I want to know if Indicador 1 has been deactivated.... in the context of Matriz Logica 1. In such a case, we only need to find out if Indicador 1 is related to Matriz Logica 1. Is Matriz Logica 1 active? Then in that context, Indicador 1 is active. Is Matriz Logica 1 inactive? Then in the context of Matriz Logica 1, Indicador 1 is inactive. The backend can always through relations to see if a parent context is active or inactive.
> 
> This issue remains unresolved, in my mind, unfortunately.

**Comment by cxelegance-unicef** [comment]
@lucasferreiraunicef @dlazaroni @ricardosreichert 
Colegas, desculpem o post/comentário grande da sexta feira. Estava com muito pra tirar da cabeça. Sendo que o Lucas confirmou com o cliente que a gente tira a relação entre "pai" e "filho" no cascade de deativação quando o filho tem relação com outros pais ainda ativas, eu atualizei esse card/issue aqui pra refletir isso.

É só importante que lembramos que, depois de deativar uma entidade, não podemos re-ativar e ter exatemente o que tinha antes de desativar. Ou seja, a deativação é irreversavel quando a gente apaga relações. O cliente deve estar satisfeito com isso ;)

**Comment by ricardosreichert** [comment]
@cxelegance-unicef Pode por favor colocar no super GET da Matriz os campos created_at e updated_at?
