### ISSUE TITLE
[NOTIFICATIONS] 

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#494]
**Lembrete:** Considerar campo "possibilidades de alerta" da atividade do plano de trabalho.

**Categorias de Notificação:**

**Transacional de Cadastro** 
      Para todo cadastro de usuário realizado dentro da plataforma, deverá ser gerado uma notificação por e-mail e interna para o usuário recém adicionado.

**Transacional de Permissão(Associação de um usuário a um Programa/Projeto)** 
      
Para toda e qualquer associacão/relacão que por ventura seja definida de um usuário para um programa/projeto, deverá ser gerado uma notificação via e-email e interna para o mesmo(usuário recém adicionado).      

**Transacional de Prazo (Alerta)** 
Alerta único avisando quanto a finalização do Programa/Projeto 6 meses antes da data final.
Enviar para o Owner do projeto ou programa.
      
**Transacional de Aprovacão** 
      
1 ) O Administrador do Programa ou Projeto receberá uma notificacão para aprovar ou rejeitar
uma versão de Matriz Lógicas e/ou Plano de trabalho.

2 ) Ao aprovar ou reprovar qualquer alteracão que exista e seja relacionada a Matriz Logica e Plano de trabalho, deverá ser gerado uma notificacão para o Administrador.

**Prototipo:** https://xd.adobe.com/view/d3a13dde-a407-4f04-b1af-6e707576a1ee-86f2/specs/

**Comment by lucasferreiraunicef** [comment]
@dlazaroni Link do protótipo

**Comment by dlazaroni** [comment]
@lucasferreiraunicef link do protótipo adicionado na descrição do épico

**Comment by lucasferreiraunicef** [comment]
Obrigado Dan, estamos juntos !

**Comment by ricardosreichert** [comment]
@lucasferreiraunicef @dlazaroni @gucostaunicef 

> **Transacional de Cadastro** é o cadastro de novo usuário?

Se a resposta for **Sim**, para o cadastro de um novo usuário, as seguintes questões poderiam ser consideradas para validação com base no fluxo de cadastro da plataforma:

- Ao cadastrar é enviado um e-mail de convite para o usuário cadastrado para ele completar e finalizar o cadastro.
- Após a conclusão do cadastro, o usuário recebe um e-mail de confirmação.

> **Transacional de Aprovação**

- Deveria existir um 3º e-mail notificando que a alteração foi realizada ou não? Esse e-mail seria enviado para todos os Admins após todos no processo de aprovação responderem.

- Se a alteração foi rejeitada ou aprovada o usuário que submeteu/solicitou a alteração deve receber um e-mail de aviso?
