### ISSUE TITLE
Estruturar as Migrations - Parte 2

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#52]

**Comment by ricardosreichert** [comment]
Updated April 27, 2022, 4:43PM
![image.png](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/fd60bd27-b53b-459b-aa5e-a46a10ff2349)

**Comment by ricardosreichert** [comment]
@jpmendesnasunicef  instalei para ajudar no trabalho
user/pass eu mando no teams
[phpMyAdmin](https://dbadmin.maap.rsr.dev.br/index.php)

**Comment by ricardosreichert** [comment]
@Clivisonc quase concluindo o schema inicial das tabelas do banco.

Tenho uma duvida sobre os Departamentos.... 

- É uma lista imutável?
- Ou é um entidade que podemos cadastrar, alterar, remover e etc?

Essas informações ajudaram a definir se vamos criar uma tabela ou um campo ENUM _(uma lista imutavel)_ dentro de uma tabela.

@ricardosreichert 

Será uma lista editável, pois poderão haver mudanças de departamento.
