### ISSUE TITLE
Acesso a atividades

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/MAAP#525]
Não está acessando atividades(Está redirecionando para Iniciativas)

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef Item será tratado na issue [#524](https://app.zenhub.com/workspaces/maap-1-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/524)

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef Item será tratado na issue [#522](https://app.zenhub.com/workspaces/maap-1-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/522)

**Comment by mfreireunicef** [comment]
Resolvido. [#35](https://github.com/UNICEF01/Sistema-MAAp-front/pull/35)
