### ISSUE TITLE
Verificar o projeto com base na LGPD/GDPR

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#54]

**Comment by ricardosreichert** [comment]
Links para o Resumo

[LGPD](https://www.notion.so/Boas-Pr-ticas-de-desenvolvimento-fb127c6834304c68aef8529f0ca80f73#90a09193e6df471a80d2e7a5b4615bf2)
[GDPR](https://www.notion.so/Boas-Pr-ticas-de-desenvolvimento-fb127c6834304c68aef8529f0ca80f73#384545cf537f4ce2b447da2af8adfd4e)

Se não funcionar os links acima, usar este link alternativo para o [Documento](https://cookie-elf-189.notion.site/Boas-Pr-ticas-de-desenvolvimento-fb127c6834304c68aef8529f0ca80f73).
