### ISSUE TITLE
Infra do Servidor - Pipeline com Codeship

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/MAAP#56]

**Comment by ricardosreichert** [comment]
CI/CD Sempre que fizer Merge / Commit na branch MASTER

[API MAAp ](https://app.codeship.com/projects/351fb715-ac74-4ca7-b576-8b1eb2a99b83)
[Front MAAp
](https://app.codeship.com/projects/3a02bf86-3389-4087-81b7-0f93523b7a91)
