### ISSUE TITLE
Contrapartida financeira - PLANO DE TRABALHO DE PROJETOS

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#662]
O valor "Contrapartida financeira (total)" em PLANO DE TRABALHO DE PROJETOS não está sendo exibido:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVJaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--901c32607afb42151718173dd2310470b901718d/image.png" alt="image.png" />

**Comment by lucasferreiraunicef** [comment]
@dlazaroni validado

**Comment by dlazaroni** [comment]
@lucasferreiraunicef validado
