### ISSUE TITLE
[Plano de Trabalho - Programas] Incluir select "direitos das crianças" e "gênero"

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#664]
A parte de gênero e direitos de crianças que constam em PRODUTO da Matriz Lógica de PROGRAMAS devem ser incluído no âmbito do plano de trabalho, sendo que diferentes **INICIATIVAS** dentro de um mesmo produto da matriz do programa pode ter diferentes graus de relevância para este indicador

<img width="1222" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d39d8dad0e8b4f7f9bdf82f20b0db17655a2791/image.png" alt="image.png" />

Definição de Preparado
- [x] Description
- [x] Regra
- [x] Exemplo/Protótipo

**Comment by lucasferreiraunicef** [comment]
Em bate papo com o Dev Marcus, definimos que será inserido no Form de INICIATIVAS. Entendemos que o cenário ideal seria este. @dlazaroni durante a homologação verifique se está de acordo.

**Comment by mfreireunicef** [comment]
Necessario fazer ajuste no backend. Front pronto.

**Comment by dlazaroni** [comment]
@mfreireunicef vou marcar a issue como concluída e gerar uma nova issue para você finalizar a implementação considerando o back. Pelos meus testes o front está ok mas a informação não está sendo armazenada, acredito que seja por conta do "ajuste no backend" que você falou.
