### ISSUE TITLE
[PROJETOS] Select de relacionamento com programas

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#666]
Atualmente, o relacionamento do projeto com programas se dá por um select de Produtos de todos os programas.

A alteração consiste em:
1) Adicionar um novo select "Selecione o programa" que fica anterior ao select atual de "Produto do programa". Quando eu seleciono um programa, o sistema filtra os produtos daquele programa

2) Quando eu estou em PLANO DE TRABALHO de PROGRAMAS e clico em adicionar novo PROJETO ou VISITA DE ESTUDO, abre-se o formulário com o select "Selecione o programa" já pré-preenchido com o programa de onde vim.

<img width="1214" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzlaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3d13c90675c110d1789aa0287d8c86b1669ce91/image.png" alt="image.png" />

Definição de Preparado
- [x] Description
- [x] Regra
- [x] Exemplo/Protótipo

**Comment by lucasferreiraunicef** [comment]
Entendemos que o SELECT de PROGRAMA servirá como START para associar e listar os produtos deste respectivo programa no SELECT de PRODUTO DE PROGRAMA.

**Comment by mfreireunicef** [comment]
1 - Acho que o que a demanda quer dizer é para criar um "select de programa" e com base no programa escolhido o select atual de "Produto de programar" vai listar apenas os produtos daquele programa.

**Comment by mfreireunicef** [comment]
2 - Depende do item 1, deve trazer ja o programa atual.

**Comment by lucasferreiraunicef** [comment]
@dlazaroni gentileza homologar

**Comment by dlazaroni** [comment]
@mfreireunicef quando tento selecionar o Programa no formulário de edição de um projeto o MAAp buga. Testei por aqui e @lucasferreiraunicef testou por lá e deu o mesmo problema

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef ainda estamos enfrentando problema de falha no carregamento deste componente objeto do card

**Comment by mfreireunicef** [comment]
Esse casso esta com um problema que so acontece em produção. A alteração trava a tela apenas em produção mesmo não tendo nenhum alert ou nenhum comportamento diferente do ambiente local.

**Comment by mfreireunicef** [comment]
Ajsute realizado e aparentimente funciou. @lucasferreiraunicef @dlazaroni porfavor testar.

**Comment by dlazaroni** [comment]
@mfreireunicef maravilha Marcus. Testei junto com o Lucas nos dois cenários e funcionou!
