### ISSUE TITLE
[Instituições] Alterações 

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#670]
1) Adicionar SELECT DE PAÍS: Seria bom poder identificar país ao inserir nova instituição no sistema.

OBS: campo não obrigatório

<img width="1174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEJhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--064ea1b6a2b9f150804953a45fa17028bd91b7be/image.png" alt="image.png" />

2) **Departamento** da Instituição deveria ser opcional, sendo que nem sempre teremos esta informação. 

Definição de Preparado
- [x] Description
- [x] Regra
- [x] Exemplo/Protótipo

**Comment by mfreireunicef** [comment]
Verificar se existe alguma tabela de pais, caso sim, verificar existencia de um endpoint. 

Caso nao exista vai ser necessario criar uma tabela com todos os paises elegiveis e em seguida criar um endpoint nba API para que seja consumido e renderizado pelo front.

**Comment by dlazaroni** [comment]
@mfreireunicef nós já temos esse select de país no formulário de PROJETOS: https://maap.org.br/project (ver em DADOS GERAIS)
<img width="1435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTdhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec327ea85d4cc7cfa73dfb806c7a363276658ad0/image.png" alt="image.png" />

**Comment by mfreireunicef** [comment]
@dlazaroni certo.

**Comment by mfreireunicef** [comment]
Necessario fazer ajuste no backend. Front pronto.

**Comment by dlazaroni** [comment]
@mfreireunicef testei e está salvando normal. ainda falta ajuste no backend?
Fechando a issue aqui
