### ISSUE TITLE
[INDICADORES] Form

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#671]
No âmbito dos indicadores, fazer os ajustes conforme print abaixo. 

1) Quebra de linha para itens com texto longo no select
2) Placeholder do campo META ANUAL: "Insira a meta anual"

<img width="1477" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f37c18e668616424591cc761c5a78d4fa5f8dd9e/image.png" alt="image.png" />

**Comment by dlazaroni** [comment]
@lucasferreiraunicef  @mfreireunicef no item 1 da descrição, o "X" unitário de cada item selecionado no select deixou de aparecer. Tudo bem dar um overflow hidden no texto, mas idealmente o título grande terminaria com "... X" (três pontinhos + X de remover):

Está assim:
<img width="1332" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUt6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f13905e0ed0fd85b546b826ec59375c3e5336c7/image.png" alt="image.png" />

Idealmente ficaria assim:
<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU96QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--333fa22f2f8eb9dc993cac5f1bd3e47fc76e72be/image.png" alt="image.png" />

**Comment by mfreireunicef** [comment]
@dlazaroni Vou verificar...
