### ISSUE TITLE
[Plano de Trabalho - Programa e Projeto] Atividade (Programa) + Tarefa (Projeto)

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#676]
Ao inserir tarefas, no plano de trabalho do projeto, é importante incluir os campos de comentários sobre lições aprendidas etc também no caso de uma tarefa ser registrada como interrompida (print 1 abaixo), como no caso de “concluída” (print 2 abaixo). 

Print 1:
<img width="1352" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzVhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abb83e6388b6983ae2b0837697bf923644694761/image.png" alt="image.png" />

Print 2:
<img width="1585" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef4dda870068a55cd6e2ee75a931e6e41aad5f12/image.png" alt="image.png" />

Definição de Preparado
- [x] Description
- [x] Regra
- [x] Exemplo/Protótipo

Critérios de Aceite:

- [x] Homologação de negócio
- [x] Componentes equivalentes ao Protótipo

**Comment by dlazaroni** [comment]
@mfreireunicef não verifiquei essa atividade no ambiente. Vou reescrever a demanda abaixo:
Para atividade do plano de trabalho de programa e para tarefa do plano de trabalho de projeto, quando selecionar o item "INTERROMPIDA" no campo "Progresso", o campo de input de "Lições aprendidas" (print 2 da descrição) deve aparecer.

**Comment by lucasferreiraunicef** [comment]
@dlazaroni

**Comment by lucasferreiraunicef** [comment]
@dlazaroni favor homologar
