### ISSUE TITLE
[Monitoramento] Ajustes

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#677]
1) Na parte de monitoramento (nível do programa e projeto), o campo “lições aprendidas” se repete. Na segunda caixa deve estar “Recomendações / Encaminhamentos” 
<img width="1174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe6dfc6f9bd88a5239ed795b8313ebbe09896220/image.png" alt="image.png" />

2) Sobre os diferentes campos de texto, seria possível abrir a caixa em full screen, para poder ver melhor o que está sendo escrito? No caso de inserir textos mais longos, fica complicado trabalhar dentro do pequeno espaço da caixa. Outro ponto relacionado é se seria possível incluir a função de poder mudar fonte, tamanho etc do texto, para poder – por exemplo – destacar títulos e de repente trabalhar com bullet points etc? 

**Sugestão:** é possível a altura do input se adequar ao tamanho do texto?

<img width="1166" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1piQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2df9304838ac1157b8aed9408d3d523500929c3b/image.png" alt="image.png" />

3) Ao salvar o formulário de monitoramento, não acontece nada. Nenhuma mensagem avisando que foi salvo etc. Porém, quando eu vou para a o menu e clico em monitoramento, está salvo. Também percebi que salvou 12 vezes??? 
Obs: se clicar mais de uma vez no botão SALVAR ele criar vários itens

<img width="1320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEJiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f1265cf92761408ad7506f5fe162c4db9991d5a/image.png" alt="image.png" />

4) Ajustar DATA de criação

**Comment by mfreireunicef** [comment]
@dlazaroni Esse item **2** acredito que essa alteração não seja viável. Seria necessário buscar e aplicar uma biblioteca de terceiros que atendesse aos requisitos necessários ou fazer isso diretamente no CSS o que seria ainda mais dispendioso e o mesmo que "reinventar a roda". Alem disso, teria que refatorar todas essas telas, não tenho informações sobre o tempo que isso demandaria nem sobre o impacto que teria no projeto.

**Comment by dlazaroni** [comment]
@mfreireunicef @lucasferreiraunicef 

- No item 1 da descrição, sumiu o placeholder "Lições Aprendidas" do primeiro campo; Além disso, o primeiro campo ficou grudado com o segundo campo:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenF6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8da43caa7af14041ecd27bc54d1f175eb2b6ac6/image.png" alt="image.png" />

- Sobre o item 2, entendo o que você mencionou no comentário. Para amenizar o problema, podemos aumentar a altura do campo? De <textarea rows="4"> para <textarea rows="8">

- No item 3, a mensagem de alert que o a reunião foi criada ou editada está ok agora, porém, quando crio uma reunião nova de monitoramento ainda tem o problema se eu clicar várias vezes em salvar ele cria vários registros iguais da mesma reunião

**Comment by mfreireunicef** [comment]
@dlazaroni Vou verificar, porem, nao entendi qual o erro do item 3, devo entao bloquear o botao apos o primeiro click?

**Comment by dlazaroni** [comment]
@mfreireunicef Isso Marcus, conforme falamos por call

**Comment by mfreireunicef** [comment]
@dlazaroni o Item 1 o erro nao consta para mim em produção (testei tanto no firefox e chrome) e esta normal, será que não foi algum tipo de cache na sua maquina? Poderia verificar novamente?

<img width="1605" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLyszQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--343fac00b197331a18310aa924b542b5f24c5251/Captura%20de%20Tela%202024-03-06%20a%CC%80s%2008.08.22.png" alt="Captura de Tela 2024-03-06 às 08.08.22.png" />

**Comment by dlazaroni** [comment]
@mfreireunicef o erro se dá somente no monitoramento de PROJETOS. Em PROGRAMAS está ok
