### ISSUE TITLE
FIX :: Analisar e corrigir o motivo do campo nao esta retornando valor correto

### ISSUE THREAD

**Issue by mfreireunicef** [UNICEF01/MAAP#683]

**Comment by mfreireunicef** [comment]
o campo é populado vindo do objetivo_especifico que fica dentro da da matriz logica, nesse caso a matriz logica 29 ( https://api.maap.org.br/api/matriz-logica/29) NAO TEM tem objetivo_especifico, possivelmente pq matriz logica de projeto nao tem objetivo especifico, preciso verificar a regrapara saber de onde pego essa informacao e alterar.

<img width="806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemhqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ec6bb519782faec6d680cc13562888ddd490351/image.png" alt="image.png" />


Ja no caso de programa essa forma funciona pois Matriz logica de programa tem (https://api.maap.org.br/api/matriz-logica/13) TEM objetivo_especifico

<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenRqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06e10b54563134ba592881334d51ea6dd756f1a9/image.png" alt="image.png" />

**Comment by lucasferreiraunicef** [comment]
@dlazaroni este foi o único item com dúvida. Gentileza verificar pois a task está explicando o bug, mas não referencia onde o mesmo ocorre.

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef Essa demanda foi criara para verificar como isso seria resolvido, a solução foi dada por @dlazaroni no teams da Daily. Com isso o item pode ser resolvido ja que foi implementado na resolução do epico.

<img width="1734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGFyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--954352e1ede622e265316018c294dcd9047bf435/Captura%20de%20Tela%202024-03-04%20a%CC%80s%2012.38.02.png" alt="Captura de Tela 2024-03-04 às 12.38.02.png" />

**Comment by dlazaroni** [comment]
@lucasferreiraunicef @mfreireunicef  validado no que se refere a issue relacionada (https://app.zenhub.com/workspaces/maap-1-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/662). Fica faltando aplicar para a tela de matriz lógica de projeto que já temos outra issue para isso: https://app.zenhub.com/workspaces/maap-1-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/656

**Comment by mfreireunicef** [comment]
@dlazaroni @lucasferreiraunicef A demanda https://app.zenhub.com/workspaces/maap-1-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/656 é o EPIC da sprint atual, ele tem duas proprias issues. Essa issues que aqui se refere apenas a https://app.zenhub.com/workspaces/maap-1-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/662 que ja foi concluida.
