### ISSUE TITLE
Indicadores - Projetos

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#696]
ao criar um novo indicador de projeto, o mesmo não pega relacionamentos de matriz lógica dos projetos.

- [x] Cenário Esperado
- [x] Componentes de acordo com protótipo
- [ ] Homologacão de Negócio

**Comment by mfreireunicef** [comment]
@dlazaroni por favor, validar.

**Comment by dlazaroni** [comment]
@mfreireunicef 
<img width="1260" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekJsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4363c2a06b57d014ea7cb7036a7e552838f0d988/image.png" alt="image.png" />
<img width="1210" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8906a13279c726d5d6bdbec8e1fdf5dc4cac027/image.png" alt="image.png" />
Ao tentar criar um indicador de projeto não apareceu nenhum item nos campos de resultado e produto acima.

Detalhe, ao criar um indicador dentro de PROGRAMA, os itens de resultado e produto apareceram resultados e produtos de PROJETO, quando deveriam trazer resultados e produtos de PROGRAMAS

**Comment by mfreireunicef** [comment]
<img width="1149" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkZsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1809fd75aa1c143f2c71a5bd83af7a6c22cf7f8c/Captura%20de%20Tela%202024-04-16%20a%CC%80s%2011.49.36.png" alt="Captura de Tela 2024-04-16 às 11.49.36.png" />
<img width="1136" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkpsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9a17d443cc2abe42a381d0a5fc639261c30e35a/Captura%20de%20Tela%202024-04-16%20a%CC%80s%2011.49.52.png" alt="Captura de Tela 2024-04-16 às 11.49.52.png" />
<img width="1104" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk5sQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4844206da65d9d34c685db9066e6ddd0c95f7047/Captura%20de%20Tela%202024-04-16%20a%CC%80s%2011.50.03.png" alt="Captura de Tela 2024-04-16 às 11.50.03.png" />

Verificando e nao consegui encontrar o erro. @dlazaroni tenta verificar um do 0 para ve se não é por lixo de banco, ja que o endpoint que retorna essas informações nao foi alterados desdo ano passado (ta da mesma forma) foi mexido apenas na exibição.

**Comment by mfreireunicef** [comment]
O erro so ocorre aparentimente ao atualziar a pagina, os campos ficam vazios.

**Comment by lucasferreiraunicef** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8694d6449acbcd6052857ddf97765bc449ed4be6/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-04-24%20a%CC%80s%2015.27.43.mov)

@dlazaroni
