### ISSUE TITLE
Indicadores - Programa

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#697]
- [ ] Cenário Esperado
- [x] Componentes de acordo com protótipo
- [ ] Homologacão de Negócio

**Comment by mfreireunicef** [comment]
@dlazaroni por favor, validar.

**Comment by dlazaroni** [comment]
@mfreireunicef ver https://app.zenhub.com/workspaces/maap-1-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/696

**Comment by mfreireunicef** [comment]
Mesmo comentario da issue https://app.zenhub.com/workspaces/maap-1-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/696

**Comment by lucasferreiraunicef** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8694d6449acbcd6052857ddf97765bc449ed4be6/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-04-24%20a%CC%80s%2015.27.43.mov)

@dlazaroni

**Comment by lucasferreiraunicef** [comment]
Evidência:
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk9PQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43d696c31cf8d4b792263ad0ed1e6add75336ff0/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-04-24%20a%CC%80s%2015.39.12.mov)

@mfreireunicef

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef A correcao dessa demanda nao foi nessa tela e sim na listagem interna que nao estava aperecendo conforme comentario:  https://app.zenhub.com/workspaces/maap-1-611ea94df0ba85000f5283bf/issues/gh/unicef01/maap/696

Mas posso verificar isso tambem, seria interessante e ser em outra issues para questoes de organizacao de demanda.

Uma observacao, tu poderia verificar na paginacao se nao esta aparecendo nas outras paginas os itens adicionados?

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef Conforme conversado na daily. Tem q verificar o que apontei acima e na daily.

**Comment by lucasferreiraunicef** [comment]
- [x] ISSUE Homologada

- [x] Cenário Esperado


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGZiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c546bcac30424556b385de22d873edea077c9f08/Gravaca%CC%83o%20MAAp.mov)
