### ISSUE TITLE
Plano de Trabalho - Iniciativa se relaciona com direito de crianças

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#698]
campo não obrigatório

- [x] Cenário Esperado
- [x] Componentes de acordo com protótipo
- [ ] Homologacão de Negócio

**Comment by lucasferreiraunicef** [comment]
Pessoal, vou pedir por gentileza que as ISSUES sejam realizadas com mais evidências e requisitos. Como realizar o teste desta maneira ? @dlazaroni

**Comment by lucasferreiraunicef** [comment]
Segue evidência:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWw0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--777b1b70f2ff8654ba23330da4f8cbec0563c387/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-04-19%20a%CC%80s%2009.19.20.mov)

**Comment by dlazaroni** [comment]
@lucasferreiraunicef @mfreireunicef tudo certo
