### ISSUE TITLE
Aprovação Matriz Lógica

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#699]
Somente administradores aprovam.

Atualmente a aprovação está sendo enviada para editores também.

- [x] Cenário Esperado
- [x] Componentes de acordo com protótipo
- [ ] Homologacão de Negócio

**Comment by lucasferreiraunicef** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGVPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88d82312b1f0993ce9db43602b01657606f79d44/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-04-24%20a%CC%80s%2015.21.38.mov)

@dlazaroni
