### ISSUE TITLE
Relatório Projeto - Ficha da Matriz Lógica

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#702]
**Protótipo:** https://xd.adobe.com/view/96091970-0811-43a2-add8-edcfccb5f0bf-c35a/screen/ce7a1419-609c-4c87-a985-b29da71dc63d/

**Páginas do protótipo:** páginas 4 e 5

**Local no front para download do relatório:** botão "..." da listagem de projetos + botão "..." da tela de visualização da matriz lógica

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3A0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddb8886c77c502b84977bab6f200af0783e577ea/image.png" alt="image.png" />

**Comment by lucasferreiraunicef** [comment]
**Issue Verificada no Contexto de Front End, hava visto que o Back será desenvolvido em uma TASK/Feature separada:**

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk81QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99cf527bcf7f844506c4696312ad5ea6638ea393/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-05-06%20a%CC%80s%2014.45.54.mov)

**Comment by dlazaroni** [comment]
@mfreireunicef os campos para baixar os relatórios estão desabilitados, é possível habilitá-los, por favor?
