### ISSUE TITLE
Indicadores - Projeto + Programa

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#703]
Indicadores de **projeto** e de **programa** são criados, são relacionados com os respectivos resultados ou produtos da matriz lógica, porém, não são exibidos na listagem de indicadores:

<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEdlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6aeeb6fe8b19fa57e46c41eae8bd16279fa2b33/image.png" alt="image.png" />

**Comment by mfreireunicef** [comment]
O erro esta na paginação. JA fiz a correção mas por algum motivo no ambiente continua errado. VOu fazer alguns testes.

**Comment by mfreireunicef** [comment]
<img width="1121" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d133d6e2d931c32fb81993e9ccaceb4b5e99d16e/Captura%20de%20Tela%202024-05-07%20a%CC%80s%2016.05.33.png" alt="Captura de Tela 2024-05-07 às 16.05.33.png" />

<img width="1275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5acbf446cf9784f608149cac42996748aa3b4fc/Captura%20de%20Tela%202024-05-07%20a%CC%80s%2016.06.27.png" alt="Captura de Tela 2024-05-07 às 16.06.27.png" />

**Comment by lucasferreiraunicef** [comment]
- [x] ISSUE Homologada

- [x] Cenário Esperado

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27a9529cc22404897a9a300eda5a4bb32d67f0a1/Gravacao%20MAAp%202.mov)
