### ISSUE TITLE
Relatório Programa - Ficha da Matriz Lógica

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#704]
https://xd.adobe.com/view/96091970-0811-43a2-add8-edcfccb5f0bf-c35a/screen/265a435f-4610-419a-92e8-2bfee4783737/

pg. 8 e 9

**Comment by lucasferreiraunicef** [comment]
**Análise**: Os componentes e Layout atendem ao cenário esperado.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHZHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db62825a2d723273566b6e2a77afc8040716c13d/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-05-08%20a%CC%80s%2016.51.25.mov)
