### ISSUE TITLE
Relatório Programa - Ficha resumida

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#705]
https://xd.adobe.com/view/96091970-0811-43a2-add8-edcfccb5f0bf-c35a/screen/4a4b3024-e83b-4e51-96b8-e91bdd65fddb/

pg 6

**Comment by lucasferreiraunicef** [comment]
**Análise:** A tarefa atingiu o cenário esperado.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVBHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c6989bc10f1a69eca336e7717ca4eb511d062d8/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-05-08%20a%CC%80s%2016.55.10.mov)

**Comment by dlazaroni** [comment]
@mfreireunicef no título "Resultados e Produtos da Matriz Lógica", alterar para "Objetivos Específicos, Resultados e Produtos da Matriz Lógica"

<img width="1022" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfd3c43fc2973eedc4802aced22967ef2f09f01f/image.png" alt="image.png" />

**Comment by mfreireunicef** [comment]
@dlazaroni esse print ai não seria de projeto? Em produto ja esta da forma que voce dafiniu no template. Verificar se não é cache....
