### ISSUE TITLE
PROGRAMAS - MATRIZ LÓGICA: aprovação

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#718]
Em PROGRAMAS - MATRIZ LÓGICA: modal de aprovação está aparecendo usuário com perfil de editor e só deve aparecer com perfil de administrador

<img width="970" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXhyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea1897f94882ed0de4a99235239ef9fc5501d7a6/image.png" alt="image.png" />
Nesse print acima o Marcus está como editor

**Comment by mfreireunicef** [comment]
Fiz a alteração em Projetos tambem. Ja que pela que lembro a regra é igual para ambos.
