### ISSUE TITLE
Programas e Projetos - Plano de trabalho - exclusão de itens

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/MAAP#723]
<img width="1564" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWk0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec4ff27fc3d1bcafb09039597d659b66b0bcd383/image.png" alt="image.png" />

O sistema deve permitir a exclusão de iniciativas e atividades criadas no plano de trabalho de programas.

O sistema deve permitir a exclusão de atividades e tarefas criadas no plano de trabalho de projetos.

**Comment by mfreireunicef** [comment]
Preciso verificar como será feito essas exlcusõies ja que temos uma sequencia logica.

**Comment by mfreireunicef** [comment]
Essa demanda foi feito a parte do front mas ainda estou tomando um erro no backend quando chamo o delete.
